# Generated by Django 5.2.7 on 2026-04-05 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Departamento')),
                ('name_short', models.CharField(max_length=100, unique=True, verbose_name='Siglas')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Curso')),
                ('name_short', models.CharField(max_length=100, unique=True, verbose_name='Código/Siglas')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taskapp.department', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año Académico')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taskapp.department', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='orden')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha de terminacion')),
                ('status', models.BooleanField(default=False, verbose_name='completada')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to=settings.AUTH_USER_MODEL, verbose_name='alumno')),
            ],
            options={
                'ordering': ['task', 'count'],
            },
        ),
        migrations.CreateModel(
            name='StageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stages/attachments/%Y/%m/%d/', verbose_name='archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='taskapp.stage', verbose_name='etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(verbose_name='fecha de terminacion')),
                ('status', models.BooleanField(default=False, verbose_name='completada')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='taskapp.course', verbose_name='cursos')),
                ('students', models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='tasks_as_student', to=settings.AUTH_USER_MODEL, verbose_name='alumnos')),
                ('tutor', models.ForeignKey(limit_choices_to={'is_tutor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_as_tutor', to=settings.AUTH_USER_MODEL, verbose_name='tutor')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='taskapp.task', verbose_name='tarea'),
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/attachments/%Y/%m/%d/', verbose_name='archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='taskapp.task', verbose_name='tarea')),
            ],
        ),
    ]
