# Generated by Django 5.2.7 on 2026-04-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_stage_options_stagefile_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='completada'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taskapp.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_short',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código/Siglas'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Departamento'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_short',
            field=models.CharField(max_length=100, unique=True, verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taskapp.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Año Académico'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='status',
            field=models.BooleanField(default=False, verbose_name='completada'),
        ),
    ]
