# Generated by Django 5.2.7 on 2026-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0003_alter_commentstage_stage_alter_commentstage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
