# Generated by Django 5.2.7 on 2026-03-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0004_alter_commenttask_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
